import { NextResponse } from "next/server"; import { z } from "zod"; import { auth } from "@/lib/auth"; import { prisma } from "@/lib/prisma"; import { cacheDelete, cacheGet, cacheSet } from "@/lib/cache"; import { cacheKeys } from "@/lib/cache-keys"; import { logActivity } from "@/lib/activity";
const schema=z.object({title:z.string().trim().min(1).max(160),targetDate:z.string().optional()});
async function uid(){const s=await auth();const e=s?.user?.email?.toLowerCase();if(!e)return null;const u=await prisma.user.findUnique({where:{email:e},select:{id:true}});return u?.id??null;}
export async function GET(){const id=await uid();if(!id)return NextResponse.json({error:"Unauthorized"},{status:401});const k=cacheKeys.goals(id);const c=await cacheGet(k);if(c)return NextResponse.json(c);const rows=await prisma.goal.findMany({where:{userId:id},orderBy:{updatedAt:"desc"}});const payload=rows.map(({progress, completed, ...goal})=>({ ...goal, completed: completed || progress === 100 }));await cacheSet(k,payload,60);return NextResponse.json(payload);}
export async function POST(req:Request){const id=await uid();if(!id)return NextResponse.json({error:"Unauthorized"},{status:401});const p=schema.safeParse(await req.json());if(!p.success)return NextResponse.json({error:"Invalid goal"},{status:400});const goal=await prisma.goal.create({data:{userId:id,title:p.data.title,completed:false,targetDate:p.data.targetDate?new Date(p.data.targetDate):undefined}});await cacheDelete(cacheKeys.goals(id));await logActivity(id,"GOAL_UPDATED",`Created goal · ${goal.title}`);return NextResponse.json(goal,{status:201});}
export async function PATCH(req:Request){const id=await uid();if(!id)return NextResponse.json({error:"Unauthorized"},{status:401});const body=await req.json() as {id?:string;completed?:boolean;title?:string};if(!body.id)return NextResponse.json({error:"Missing id"},{status:400});const result=await prisma.goal.updateMany({where:{id:body.id,userId:id},data:{...(typeof body.completed==="boolean"?{completed:body.completed,progress:body.completed?100:0}:{}),...(body.title?.trim()?{title:body.title.trim()}: {})}});if(!result.count)return NextResponse.json({error:"Goal not found"},{status:404});await cacheDeleteManySafe(id);return NextResponse.json({ok:true});}
async function cacheDeleteManySafe(id:string){await cacheDelete(cacheKeys.goals(id));await cacheDelete(cacheKeys.dashboard(id));}

export async function DELETE(req:Request){const id=await uid();if(!id)return NextResponse.json({error:"Unauthorized"},{status:401});const goalId=new URL(req.url).searchParams.get("id");if(!goalId)return NextResponse.json({error:"Missing id"},{status:400});const result=await prisma.goal.deleteMany({where:{id:goalId,userId:id}});if(!result.count)return NextResponse.json({error:"Goal not found"},{status:404});await cacheDelete(cacheKeys.goals(id));await cacheDelete(cacheKeys.dashboard(id));return NextResponse.json({ok:true});}
