import { NextResponse } from "next/server"; import { auth } from "@/lib/auth"; import { prisma } from "@/lib/prisma"; import { cacheDelete, cacheGet, cacheSet } from "@/lib/cache"; import { cacheKeys } from "@/lib/cache-keys"; import { z } from "zod"; import { logActivity } from "@/lib/activity";
const schema=z.object({amount:z.coerce.number().positive(),name:z.string().min(1).max(120),category:z.enum(["FOOD","DRINKS","TRANSPORT","SHOPPING","ENTERTAINMENT","EDUCATION","HEALTH","BILLS","OTHER"]),spentAt:z.string(),note:z.string().max(300).optional()});
const patchSchema=z.object({id:z.string(),amount:z.coerce.number().positive().optional(),name:z.string().min(1).max(120).optional(),category:z.enum(["FOOD","DRINKS","TRANSPORT","SHOPPING","ENTERTAINMENT","EDUCATION","HEALTH","BILLS","OTHER"]).optional(),spentAt:z.string().optional(),note:z.string().max(300).optional()});
async function uid(){const s=await auth();const e=s?.user?.email?.toLowerCase();if(!e)return null;const u=await prisma.user.findUnique({where:{email:e},select:{id:true}});return u?.id??null;}
export async function GET(req:Request){const id=await uid();if(!id)return NextResponse.json({error:"Unauthorized"},{status:401});const q=new URL(req.url).searchParams;const from=q.get("from");const to=q.get("to");const hasRange=Boolean(from||to);const range=q.get("range")??"all";const key=cacheKeys.expenses(id,range+":"+(from??"")+":"+(to??""));if(!hasRange){const c=await cacheGet(key);if(c)return NextResponse.json(c);}const where:any={userId:id};if(from||to)where.spentAt={...(from?{gte:new Date(from)}:{}),...(to?{lte:new Date(to)}:{})};const rows=await prisma.expense.findMany({where,orderBy:{spentAt:"desc"},take:500});if(!hasRange)await cacheSet(key,rows,45);return NextResponse.json(rows);}
export async function POST(req:Request){const id=await uid();if(!id)return NextResponse.json({error:"Unauthorized"},{status:401});const p=schema.safeParse(await req.json());if(!p.success)return NextResponse.json({error:"Invalid expense"},{status:400});const body=p.data;const expense=await prisma.expense.create({data:{userId:id,amount:Math.round(body.amount*100),name:body.name,category:body.category,spentAt:new Date(body.spentAt),note:body.note}});await logActivity(id,"EXPENSE_ADDED",`Added ₹${body.amount.toFixed(0)} · ${body.name}`);await cacheDelete(cacheKeys.expenses(id,"all::"));await cacheDelete(cacheKeys.dashboard(id));return NextResponse.json(expense,{status:201});}

export async function PATCH(req:Request){const id=await uid();if(!id)return NextResponse.json({error:"Unauthorized"},{status:401});const p=patchSchema.safeParse(await req.json());if(!p.success)return NextResponse.json({error:"Invalid expense"},{status:400});const d=p.data;const result=await prisma.expense.updateMany({where:{id:d.id,userId:id},data:{...(d.amount!==undefined?{amount:Math.round(d.amount*100)}:{}),...(d.name!==undefined?{name:d.name}:{}),...(d.category!==undefined?{category:d.category}:{}),...(d.spentAt!==undefined?{spentAt:new Date(d.spentAt)}:{}),...(d.note!==undefined?{note:d.note}: {})}});if(!result.count)return NextResponse.json({error:"Expense not found"},{status:404});await cacheDelete(cacheKeys.expenses(id,"all::"));await cacheDelete(cacheKeys.dashboard(id));return NextResponse.json({ok:true});}
export async function DELETE(req:Request){const id=await uid();if(!id)return NextResponse.json({error:"Unauthorized"},{status:401});const expenseId=new URL(req.url).searchParams.get("id");if(!expenseId)return NextResponse.json({error:"Missing id"},{status:400});const result=await prisma.expense.deleteMany({where:{id:expenseId,userId:id}});if(!result.count)return NextResponse.json({error:"Expense not found"},{status:404});await cacheDelete(cacheKeys.expenses(id,"all::"));await cacheDelete(cacheKeys.dashboard(id));return NextResponse.json({ok:true});}
