"use client";
import { useState } from "react";

function localDateTimeValue(date = new Date()) { const pad = (n:number) => String(n).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }

export default function ExpenseForm({ onCreated }: { onCreated: () => void }) {
  const [amount,setAmount]=useState(""); const [name,setName]=useState(""); const [category,setCategory]=useState("FOOD"); const [spentAt,setSpentAt]=useState(localDateTimeValue()); const [busy,setBusy]=useState(false); const [done,setDone]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setDone("");const r=await fetch("/api/expenses",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount,name,category,spentAt})});setBusy(false);if(!r.ok)return setDone((await r.json().catch(()=>({}))).error??"Could not save this expense.");setAmount("");setName("");setSpentAt(localDateTimeValue());setDone("Saved.");onCreated();}
  return <form onSubmit={submit} className="flow-card rounded-3xl p-5"><div className="text-sm text-black/45">Record an expense</div><div className="mt-5 space-y-3"><input autoFocus value={amount} onChange={e=>setAmount(e.target.value)} className="flow-input text-3xl font-semibold" type="number" min="0.01" step="0.01" placeholder="₹0" required/><input value={name} onChange={e=>setName(e.target.value)} className="flow-input" placeholder="What was it?" required/><select value={category} onChange={e=>setCategory(e.target.value)} className="flow-input"><option value="FOOD">Food</option><option value="DRINKS">Drinks</option><option value="TRANSPORT">Transport</option><option value="SHOPPING">Shopping</option><option value="ENTERTAINMENT">Entertainment</option><option value="EDUCATION">Education</option><option value="HEALTH">Health</option><option value="BILLS">Bills</option><option value="OTHER">Other</option></select><label className="block text-xs text-black/40">When did you spend it?</label><input value={spentAt} onChange={e=>setSpentAt(e.target.value)} className="flow-input" type="datetime-local" required/><button disabled={busy} className="w-full rounded-2xl bg-black px-4 py-3 text-sm font-medium text-white">{busy?"Saving…":"Add expense"}</button>{done&&<div className="text-xs text-black/45">{done}</div>}</div></form>
}
